# Generated by Django 6.0.7 on 2026-07-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
        ('telegram_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Internal name for this template.', max_length=255, verbose_name='Template Title')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('VOICE', 'Voice Note')], default='TEXT', max_length=20, verbose_name='Message Type')),
                ('text_content', models.TextField(blank=True, help_text='The message text. Can also be used as a caption for voice/media.', verbose_name='Text Content')),
                ('voice_file', models.FileField(blank=True, help_text='Must be an .ogg file with OPUS codec for Telegram Voice Notes.', null=True, upload_to='sender/voices/', verbose_name='Voice File (.ogg)')),
                ('telegram_file_id', models.CharField(blank=True, help_text='Auto-filled after the first upload to prevent re-uploading and spam flags.', max_length=255, verbose_name='Telegram File ID')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Campaign Title')),
                ('only_premium_users', models.BooleanField(default=False, help_text='Target only Telegram Premium users.', verbose_name='Only Premium Users')),
                ('daily_limit_per_account', models.PositiveIntegerField(default=25, help_text='Max messages an account will send per day before resting.', verbose_name='Daily Limit Per Account')),
                ('delay_between_messages', models.PositiveIntegerField(default=60, help_text='Base delay between messages. System will add random jitter to this.', verbose_name='Base Delay (Seconds)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('users_messaged', models.PositiveIntegerField(default=0, verbose_name='Total Users Messaged')),
                ('execution_accounts', models.ManyToManyField(blank=True, help_text='Accounts to rotate for sending messages. If empty, the system can auto-select active ones.', related_name='sender_tasks', to='telegram_account.telegramaccount', verbose_name='Execution Accounts')),
                ('target_sources', models.ManyToManyField(help_text='Only send to users extracted from these groups/channels.', related_name='sender_tasks', to='crawler.telegramsource', verbose_name='Target Sources')),
            ],
            options={
                'verbose_name': 'Sender Task',
                'verbose_name_plural': 'Sender Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='1 is sent first, 2 is sent second, etc.', verbose_name='Sending Order')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.messagetemplate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.sendertask')),
            ],
            options={
                'verbose_name': 'Task Message',
                'verbose_name_plural': 'Task Messages',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'order')},
            },
        ),
        migrations.AddField(
            model_name='sendertask',
            name='messages',
            field=models.ManyToManyField(related_name='sender_tasks', through='sender.TaskMessage', to='sender.messagetemplate', verbose_name='Messages to Send'),
        ),
    ]
