# Generated by Django 6.0.7 on 2026-07-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
        ('sender', '0001_initial'),
        ('telegram_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendertask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='sendertask',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='sendertask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
        migrations.AddIndex(
            model_name='sendertask',
            index=models.Index(fields=['status', '-created_at'], name='sender_send_status_f91a91_idx'),
        ),
    ]
