# Generated by Django 6.0.7 on 2026-07-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_sendertask_completed_at_sendertask_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='telegram_file_id',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='telegram_file_cache',
            field=models.JSONField(blank=True, default=dict, help_text="Stores message IDs per account. Format: {'account_id': message_id}", verbose_name='Telegram File Cache'),
        ),
    ]
