# Generated by Django 6.0.7 on 2026-07-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', help_text='Name of the group/channel for easy identification.', max_length=255, verbose_name='Chat Title')),
                ('link', models.CharField(help_text='Public username (@group) or private invite link.', max_length=255, unique=True, verbose_name='Link or Username')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Internal Telegram ID if resolved.', null=True, unique=True, verbose_name='Telegram Chat ID')),
                ('chat_type', models.CharField(choices=[('GROUP', 'Group / Supergroup'), ('CHANNEL', 'Channel')], default='GROUP', max_length=20, verbose_name='Chat Type')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop crawling or messaging users from this source.', verbose_name='Is Active')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Crawled At')),
            ],
            options={
                'verbose_name': 'Telegram Source',
                'verbose_name_plural': 'Telegram Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawl_method', models.CharField(choices=[('GROUP_HISTORY', 'Group History (Messages)'), ('CHANNEL_COMMENTS', 'Channel Comments')], default='GROUP_HISTORY', max_length=50, verbose_name='Crawl Method')),
                ('target_user_count', models.PositiveIntegerField(default=100, help_text='Stop crawling when this many unique users are extracted.', verbose_name='Target User Count')),
                ('message_scan_limit', models.PositiveIntegerField(default=10000, help_text='Stop crawling after traversing this many messages, regardless of user count.', verbose_name='Message Scan Limit')),
                ('include_admins', models.BooleanField(default=False, help_text='If False, attempts to skip group administrators (if detectable).', verbose_name='Include Admins')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt Count')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('users_crawled', models.PositiveIntegerField(default=0, help_text='Current count of successfully extracted users.', verbose_name='Users Crawled')),
                ('messages_scanned', models.PositiveIntegerField(default=0, help_text='Current count of messages traversed in this task.', verbose_name='Messages Scanned')),
                ('last_message_id', models.BigIntegerField(blank=True, help_text='ID of the last message processed. Used to resume crawling.', null=True, verbose_name='Last Message ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('execution_account', models.ForeignKey(blank=True, help_text='The Telegram account used to run this crawler.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_tasks', to='telegram_account.telegramaccount', verbose_name='Execution Account')),
                ('source', models.ForeignKey(help_text='The group or channel to crawl.', on_delete=django.db.models.deletion.CASCADE, related_name='crawler_tasks', to='crawler.telegramsource', verbose_name='Target Source')),
            ],
            options={
                'verbose_name': 'Crawler Task',
                'verbose_name_plural': 'Crawler Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, db_index=True, help_text='Without @ symbol. Can be null if user has no username.', max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Is Bot')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Ready to message)'), ('IN_QUEUE', 'In Queue for messaging'), ('MESSAGED', 'Message Sent'), ('REPLIED', 'Replied (Engaged)'), ('FAILED', 'Failed to send (Blocked/Privacy)')], db_index=True, default='PENDING', max_length=20, verbose_name='Messaging Status')),
                ('last_messaged_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Messaged At')),
                ('crawled_by_account', models.ForeignKey(blank=True, help_text='The specific account that scraped this user. Useful for rotation logic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_leads', to='telegram_account.telegramaccount', verbose_name='Crawled By Account')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_users', to='crawler.crawlertask', verbose_name='Source Task')),
                ('source_chat', models.ForeignKey(blank=True, help_text='The actual group/channel this user was found in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_users', to='crawler.telegramsource', verbose_name='Source Chat')),
            ],
            options={
                'verbose_name': 'Crawled User',
                'verbose_name_plural': 'Crawled Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['status', '-created_at'], name='crawler_cra_status_123435_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['execution_account', 'status'], name='crawler_cra_executi_35a2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleduser',
            index=models.Index(fields=['status', '-created_at'], name='crawler_cra_status_a2b921_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleduser',
            index=models.Index(fields=['source_chat'], name='crawler_cra_source__eb1b40_idx'),
        ),
    ]
