# Generated by Django 6.0.7 on 2026-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(help_text='example: +989123456789', max_length=20, unique=True, verbose_name='phone number')),
                ('api_id', models.IntegerField(verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=150, verbose_name='API Hash')),
                ('session_path', models.CharField(blank=True, help_text='created automatically', max_length=255, verbose_name='session path')),
                ('is_active', models.BooleanField(default=False, verbose_name='active(login)')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='(Spam Block)')),
                ('restricted_until', models.DateTimeField(blank=True, null=True, verbose_name='restricted until')),
                ('daily_messages_sent', models.PositiveIntegerField(default=0, verbose_name='daily messages sent')),
                ('last_message_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last message sent at')),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
                'db_table': 'telegram_accounts',
            },
        ),
    ]
